const Item  = {
    "id":"e1Z6SP5Egkr1i/8fu1Rm5ORpmbSVx/6q3ZAvSJdt8AQ=_16bf06ad6d2:4e0c9:dd8759",
    "originId":"https://reactdigest.net/digests/208",
    "fingerprint":"cc1db306",
    "title":"Weekly React Digest Issue #208",
    "author":"Jakub Chodounsky",
    "summary":{
        "content":"<h2>sponsor</h2>\n<div>\n<p><a href=\"https://reactdigest.net/links/6703/redirect?medium=rss\" target=\"_blank\">Spend Less Time Sweating Over the UI in Your React Apps</a></p>\n<p>Get started with KendoReact’s 55+ professionally developed UI and data visualization components and cut down on the development time of your React apps. With its wide range of customizable components, from the essential to the advanced, it can augment any existing development stack. Try now 30 days for free.</p>\n</div>\n<h2>react</h2>\n<div>\n<p><a href=\"https://reactdigest.net/links/7047/redirect?medium=rss\" target=\"_blank\">Nodejs Starter - Full-Stack React Material Kit</a></p>\n<p>You may not use before a boilerplate, and this is ok, but in my case, when I start a new project in Nodejs, I try to avoid much as I can to code the bottom layer of the product. This phase usually, is boring, not so creative and relatively time-consuming.</p>\n</div>\n<div>\n<p><a href=\"https://reactdigest.net/links/7065/redirect?medium=rss\" target=\"_blank\">ReactJS Interview Questions for Senior Developers</a></p>\n<p>You can work with React for years and actually have no opinion on some of the less practical questions and it’s fine. However, if you have an interview, then it’s quite important to have an opinion. Why? Well, first, it feels good to be able to answer interviewer’s questions and also shows your interest in the subject.</p>\n</div>\n<div>\n<p><a href=\"https://reactdigest.net/links/7060/redirect?medium=rss\" target=\"_blank\">Web Accessibility Guidebook for Developers</a></p>\n<p>In the process of implementing accessibility compliance (Section 508, WCAG 2.0 and WAI-ARIA) for KendoReact, our suite of native UI components for React, we learned a lot about both fundamental and advanced accessibility topics. With this article, our goal is to introduce fellow engineers, regardless of level, to web accessibility and share our practical knowledge and best practices.</p>\n</div>\n<div>\n<p><a href=\"https://reactdigest.net/links/7064/redirect?medium=rss\" target=\"_blank\">React base table</a></p>\n<p>A react table component to display large datasets with high performance and flexibility.</p>\n</div>\n<div>\n<p><a href=\"https://reactdigest.net/links/7059/redirect?medium=rss\" target=\"_blank\">Framer Motion</a></p>\n<p>An open source React library to power production-ready animations. Design fluid animations for the web, across desktop and mobile.</p>\n</div>\n<h2>events</h2>\n<div>\n<p><a href=\"https://reactdigest.net/links/7049/redirect?medium=rss\" target=\"_blank\">Become a speaker at React Advanced Conference (Oct 25, London)</a></p>\n<p>Are you looking for an awesome conf to present your React (Native) talk? The React Advanced CFP is open until the end of July. Submit your proposal, and become a part of the star-studded lineup! 🌟</p>\n</div>",
        "direction":"ltr"
    },
    "alternate":[
        {
            "href":"http://feedproxy.google.com/~r/digest-react/~3/BHu8H-8K8lg/208",
            "type":"text/html"
        }
    ],
    "canonical":[
        {
            "href":"https://reactdigest.net/digests/208",
            "type":"text/html"
        }
    ],
    "crawled":1563106662098,
    "published":1563105599000,
    "origin":{
        "streamId":"feed/http://feeds.feedburner.com/digest-react",
        "title":"Weekly React Digest",
        "htmlUrl":"https://reactdigest.net"
    },
    "unread":true,
    "categories":[
        {
            "id":"user/5f978fd3-1090-432c-bdd9-fec8395289c4/category/2e702d82-a087-43fe-8694-d9598b01b104",
            "label":"CatchUp"
        }
    ],
    "commonTopics":[
        {
            "id":"nlp/f/topic/20",
            "label":"accessibility"
        },
        {
            "score":43.86929081971449,
            "id":"nlp/f/topic/3001",
            "salienceLevel":"about",
            "label":"programming"
        },
        {
            "score":29.587415211733898,
            "id":"nlp/f/topic/1169",
            "salienceLevel":"about",
            "label":"innovation"
        }
    ],
    "entities":[
        {
            "mentions":[
                {
                    "text":"ReactJS"
                },
                {
                    "text":"React"
                }
            ],
            "id":"nlp/f/entity/wd:19399674",
            "salienceLevel":"about",
            "label":"ReactJS"
        },
        {
            "mentions":[
                {
                    "text":"Native"
                }
            ],
            "id":"nlp/f/entity/wd:169480",
            "salienceLevel":"mention",
            "label":"Indigenous species"
        },
        {
            "mentions":[
                {
                    "text":"data visualization"
                }
            ],
            "id":"nlp/f/entity/wd:6504956",
            "salienceLevel":"mention",
            "label":"data visualization"
        },
        {
            "mentions":[
                {
                    "text":"London"
                }
            ],
            "id":"nlp/f/entity/wd:84",
            "salienceLevel":"mention",
            "label":"London"
        },
        {
            "mentions":[
                {
                    "text":"Section"
                }
            ],
            "id":"nlp/f/entity/wd:67828",
            "salienceLevel":"mention",
            "label":"Section"
        }
    ]
},